# Generated by Django 6.0.3 on 2026-03-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_code_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Условие задачи (Markdown)')),
            ],
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='event_type',
            field=models.CharField(choices=[('join', 'Join'), ('leave', 'Leave'), ('copy', 'Copy'), ('paste', 'Paste'), ('paste_blocked', 'Paste Blocked'), ('blur', 'Blur')], max_length=15),
        ),
        migrations.AddField(
            model_name='session',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task'),
        ),
    ]
