# Generated by Django 6.0.3 on 2026-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_alter_actionlog_event_type_session_current_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current_task',
        ),
        migrations.AddField(
            model_name='session',
            name='task_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
