# Generated by Django 5.2 on 2025-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='code_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
